### ISSUE TITLE
FFMPEG errors

### ISSUE THREAD

**Issue by DanAustinGH** [craigmox/cetonproxy#19]
Received a used eth6 and have it paired with the cable co.  The channel map looks odd, like a mix of the previous cable co and my own.  Ignoring that, I did spot channels I knew were valid and checked them.

The lineup.xml is valid, but I am not able to tune with vlc or emby.  Both eventually timeout and the  cetonproxydefault.log has an error about not finding codec parameters for streams.  The videotest also fails with a similar error.  This happens with 57 release on Windows 10, and a 64 bit version compile for use with Wine on Linux.

The unit arrived with v14 firmware and I have upgraded to the v15, with no change in results.

**Comment by craigmox** [comment]
Hey, can you upload your log somewhere and post it?  Most of those find codec parameter errors are not truly errors.  The ceton sends out data with a bunch of invalid video streams, where only one actually contains data, so FFMPEG complains about those other ones.  It sounds like it's not finding any valid video stream, though, so is it possible the device is not fully paired with your cable?  While you're attempting to watch a channel, does the tuner status page on the device show anything odd?  Does the "Card Authorization" on the CableCARD page show something like "Validated, validation message is received, authenticated, and the IDs match those in the current binding"?

**Comment by DanAustinGH** [comment]
the log is at https://www.fitawi.com/cetondefault.log 

The card was authenticated and validated. and the tuner showed an active channel with streaming settings that seemed to match the requesting client (either the emby server or VLC).  Since I foolishly used my only cablecard, I ended up calling support back and re-pairing it to my original device.  Next week I will try to get another card

The Channels monitor on cetonproxy showed the correct channel, with it active and a reasonable media rate, so the FFMPEG errors might well be a red herring.  One possible issue on both the Linux and WIndows boxes is that they all have multiple network cards, and I left the advanced settings alone.  That worked well enough to interact with the lineup.xml, but may have had an impact on media streaming.

It is also possible I have bought a broken eth6.

**Comment by craigmox** [comment]
Thanks for the log.  At one point in the log it looks like it was going to work:

  [2020-11-05 17:10:43.705] Packet out of order on tuner 0: -65535

That message means it received at least 65535 packets from the tuner, which is quite a bit more than needed in order to be showing video.  Its supposed to show the FFMPEG messages when it figures out what's in the stream, which is supposed to happen way before it receives that many packets.  It seems like it's struggling to find anything useful in the data.

Then the rest of the log kind of goes to hell.. device didn't seem like it wanted to respond to tuning at all.

I don't think this is a network related issue, at least from cetonproxy's perspective.  It's able to receive HTTP requests, and it's able to talk to the device and receive some kind of data from it, so that's all that should be needed.

Next time you can test, maybe try taking cetonproxy out of the equation?  On Windows I've been able to use VLC to receive video directly from the ceton using RTP.  I can write up instructions if you're interested.  Also, I searched for a way to do it on Linux and people are saying "VLC can directly access the video through /dev/cetonx on Linux."  Maybe that means something to you.

**Comment by DanAustinGH** [comment]
I would be interested in RTP/VLC hints.  I tried to do just that and had no success, but that could well be that I wasn't doing it right.

The Linux box is my media server, and all 'consumption' tests are from a Win10 box.  One more point, those logs are from the instance running under Wine on Linux.  I did try on my Win10 desktop and had the same results.  Will update as soon as I can

**Comment by DanAustinGH** [comment]
It took a week to get another card from the cable co.  None in stock, and once they found some they forgot to add them to their inventory system, so it could not be paired.

I can confirm that a recompiled 64 bit version does work on Wine.  A little slow to tune, 6~8 seconds, but usable.  Now I need to figure out if there is a way to purge the channel listing, as the unit came with a full channel list from another cable co, and only a handful of the local channel listing is being imported.

**Comment by DanAustinGH** [comment]
Any chance you can provide the instructions on using vlc to receive the stream from the Ceton directly?
I have tried every example I can find online without success...
